name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-cli:
    name: Nix build trilby-cli
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v31
    - uses: ryanccn/attic-action@v0
      with:
        endpoint: https://cache.ners.ch
        cache: haskell
        token: ${{ secrets.ATTIC_TOKEN }}
    - name: Build
      run: nix build --accept-flake-config .#trilby-cli
    - name: Closure size
      run: nix path-info -sSh ./result* | sed 's,/nix/store.[^-]\+-,,' | sort
  build:
    name: Nix build all toplevels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wimpysworld/nothing-but-nix@v6
      with:
        nix-permission-edict: true
    - uses: nixbuild/nix-quick-install-action@v31
    - uses: ryanccn/attic-action@v0
      with:
        endpoint: https://cache.ners.ch
        cache: trilby
        token: ${{ secrets.ATTIC_TOKEN }}
    - name: Build
      run: nix build --accept-flake-config --print-build-logs .#trilby-all-toplevel
    - name: Closure size
      run: nix path-info -Sh ./result/* | sed 's,/nix/store.[^-]\+-,,' | sort
  check:
    name: Nix check
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: wimpysworld/nothing-but-nix@v6
      with:
        nix-permission-edict: true
    - uses: nixbuild/nix-quick-install-action@v31
    - name: Check
      run: nix flake check --accept-flake-config
