name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-cli:
    name: Build trilby-cli
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ners/simply-nix@main
    - uses: ryanccn/attic-action@v0
      with:
        endpoint: https://cache.ners.ch
        cache: haskell
        token: ${{ secrets.ATTIC_TOKEN }}
    - name: Build
      run: nix build --accept-flake-config .#trilby-cli
    - name: Closure size
      run: nix path-info -sSh ./result* | sed 's,/nix/store.[^-]\+-,,' | sort
  build:
    name: Build all toplevels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ners/simply-nix@main
      with:
        reclaim_space: true
    - uses: ryanccn/attic-action@v0
      with:
        endpoint: https://cache.ners.ch
        cache: trilby
        token: ${{ secrets.ATTIC_TOKEN }}
    - name: Build
      run: nix build --accept-flake-config --print-build-logs .#trilby-all-toplevel
    - name: Closure size
      run: nix path-info -Sh ./result/* | sed 's,/nix/store.[^-]\+-,,' | sort
  check:
    name: Flake check
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ners/simply-nix@main
      with:
        reclaim_space: true
    - name: Flake check
      run: nix flake check --accept-flake-config
